#! /usr/bin/env python3
# -*- coding: UTF-8 -*-
#----------------------------------------------------------------------
#--- Python Build file for application arm_interrupt
#--- automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
#--- from root OIL file turn_light.oil
#---
#--- Compiling a Trampoline application is done in 2 stages
#--- 1 - From the OIL file, a set of files is generated as long as
#---     build options. Among these files are the build.py and make.py
#---     files. make.py contains compilation rules when the OIL file
#---     and the included OIL files are modified. make.py is only
#---     written once when the goil command is typed.
#--- 2 - From all the C/assembly files (OS, Application, librairies,
#---     configuration, ...), the objects and the executable are
#---     produced. This is done by the build.py file.
#---     build.py is generated each time goil is called by make.py
#----------------------------------------------------------------------

import sys, os, subprocess, string
from string import Template

#--- Add some function for Python3 support

if sys.version_info[0] >=3 :
    def bytesdecode(obj) :
        return obj.decode(sys.stdout.encoding)
else :
    def bytesdecode(obj) :
        return obj

#--- Add the location of makefile.py to the import path
sys.path.append("/Users/alejandrocalderonaveitua/autosar/trampoline/make")

#--- Import the makefile system in python
import makefile, projfile

#--- To work with relative paths
scriptDir = os.path.dirname (os.path.abspath (sys.argv[0]))
os.chdir (scriptDir)

#--- Get goal as first argument
askedGoal = "all"
if len (sys.argv) > 1 :
  askedGoal = sys.argv [1]

if askedGoal == "all" or askedGoal == "clean" :
  goal = askedGoal
else :
  goal = "all"

#--- Get max parallel jobs as second argument
maxParallelJobs = 0 # 0 means use host processor count
if len (sys.argv) > 2 :
  maxParallelJobs = int (sys.argv [2])

#--- Instanciate a new makefile object
make = makefile.Make(goal)

#----------------------------------------------------------------------
#--- Various variables used after
#----------------------------------------------------------------------
compiler = r"arm-none-eabi-gcc"
cppCompiler = r"g++"
linker = r"arm-none-eabi-ld"
assembler = r"./arm-wrapper.sh"
autosar = True
autosar_sc = 1
autosar_osapplications = False
with_ioc = False
with_com = False
scheduler = "osek"
trampoline_base_path = "/Users/alejandrocalderonaveitua/autosar/trampoline/"
cflags = []
cppflags = []
ldflags = []
asflags = []
# flags that should appear at the beginning of the command.
precflags = []
precppflags = []
preldflags = []
preasflags = []
includeDirs = []

cflags += "-mcpu=cortex-a7 -mfpu=vfpv4 -marm -std=gnu99 -I. -I./turn_light -I/Users/alejandrocalderonaveitua/autosar/trampoline/os -I/Users/alejandrocalderonaveitua/autosar/trampoline/autosar".split()
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7"]
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve"]
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve/board"]
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve/libs/pic"]
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve/libs/serial"]
includeDirs += ["-I","/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve/libs/timer"]
if with_ioc:
  includeDirs += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/ioc"]
includeDirs += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/com"]
includeDirs += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/os"]
includeDirs += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/debug"]
includeDirs += ["-I", "turn_light"]
cflags   += includeDirs
cppflags += includeDirs
asflags  += includeDirs

asflags += "-mcpu=cortex-a7 -marm -I. -I./turn_light -I/Users/alejandrocalderonaveitua/autosar/trampoline/os -I/Users/alejandrocalderonaveitua/autosar/trampoline/autosar".split()

#----------------------------------------------------------------------
#--- Try to detect automatically the location of libc and libgcc
#--- This supposes the compiler has a (something)-gcc name
#--- for non posix target
#----------------------------------------------------------------------
if "gcc" in compiler:
  compilerFullPath = makefile.find_executable(compiler)
  if compilerFullPath != None:
    #--- Extract the (something) from the compiler executable name
    compilerParts = compiler.split('-')
    compilerParts.pop()
    compilerPrefix = "-".join(compilerParts)
    #--- Get the full path of the compiler
    compilerToolChainPath = os.path.dirname(os.path.dirname(compilerFullPath))
    #--- Get the version of the compiler, [:-1] removes the carriage return
    compilerVersion = subprocess.check_output([compiler, '-dumpversion'])[:-1]
    #--- Build the libc and libgcc paths
    procLibc  =subprocess.Popen([compilerFullPath,"-print-file-name=libc.a"]+cflags,stdout=subprocess.PIPE)
    procLibgcc=subprocess.Popen([compilerFullPath,"-print-libgcc-file-name"]+cflags,stdout=subprocess.PIPE)
    procLibc.wait()
    procLibgcc.wait()
    libcPath = os.path.dirname(procLibc.stdout.readline().strip())
    libgccPath = os.path.dirname(procLibgcc.stdout.readline().strip())
    #--- Add both to linker flags
    ldflags += ['-L' + bytesdecode(libcPath), '-lc']
    ldflags += ['-L' + bytesdecode(libgccPath), '-lgcc']

#----------------------------------------------------------------------
#--- Build the source files list
#----------------------------------------------------------------------
cSourceList = []
cppSourceList = []
sSourceList = []
oilSourceList = []

#--- OIL file
oilSourceList.append("turn_light.oil")

#--- Kernel files 
cSourceList.append(projfile.ProjectFile("os/tpl_os_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_timeobj_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_action.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_error.c", trampoline_base_path))
cflags += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/autosar"]
cppflags += ["-I", "/Users/alejandrocalderonaveitua/autosar/trampoline/autosar"]
cSourceList.append(projfile.ProjectFile("autosar/tpl_as_action.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_os_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_os.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_interrupt_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("os/tpl_os_task_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("autosar/tpl_as_counter_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("autosar/tpl_as_st_kernel.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("autosar/tpl_as_isr_kernel.c", trampoline_base_path))

#--- Add C files of the application
cSourceList.append(projfile.ProjectFile("turn_light.c"))

#--- Add generated files
cSourceList.append(projfile.ProjectFile("turn_light/tpl_app_config.c"))

cSourceList.append(projfile.ProjectFile("turn_light/tpl_os.c"))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/tpl_machine_arm.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/bouchons.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_entry_v7.S", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_cache_v7.S", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_mmu_v7.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_heap.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_irq.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_stdio.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_string.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_math.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/arm_main.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/board/arm_board.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/libs/pic/gic.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/libs/serial/pl01x.c", trampoline_base_path))
cSourceList.append(projfile.ProjectFile("machines/virt-v7/armv7ve/libs/timer/generic_timer.c", trampoline_base_path))
#----------------------------------------------------------------------
#--- Build the object list and the compiler dependancies
#----------------------------------------------------------------------
objectList = []

for sourceFile in cSourceList:
  source = sourceFile.src()
  object = sourceFile.obj("build")
  depObject = sourceFile.dep("build")
  objectList.append(object)
  rule = makefile.Rule([object], "Compiling " + source)
  rule.deleteTargetDirectoryOnClean()
  rule.mDependences.append(source)
  rule.mCommand.append(compiler)
  rule.mCommand += precflags
  rule.mCommand += ["-c", source]
  rule.mCommand += ["-o", object]
  rule.mCommand += ["-MD", "-MP", "-MF", depObject]
  rule.mCommand += cflags
  rule.enterSecondaryDependanceFile (depObject, make)
  make.addRule(rule)

for sourceFile in cppSourceList:
  source = sourceFile.src()
  object = sourceFile.obj("build")
  depObject = sourceFile.dep("build")
  objectList.append(object)
  rule = makefile.Rule([object], "Compiling " + source)
  rule.deleteTargetDirectoryOnClean()
  rule.mDependences.append(source)
  rule.mCommand.append(cppCompiler)
  rule.mCommand += precppflags
  rule.mCommand += ["-c", source]
  rule.mCommand += ["-o", object]
  rule.mCommand += ["-MD", "-MP", "-MF", depObject]
  rule.mCommand += cppflags
  rule.enterSecondaryDependanceFile (depObject, make)
  make.addRule(rule)

for sourceFile in sSourceList:
  source = sourceFile.src()
  object = sourceFile.obj("build")
  objectList.append(object)
  rule = makefile.Rule([object], "Assembling " + source)
  rule.mDependences.append(source)
  rule.mCommand.append(assembler)
  rule.mCommand += preasflags
  rule.mCommand += ["-c", source]
  rule.mCommand += ["-o", object]
  rule.mCommand += asflags
  make.addRule(rule)

product = "turn_light_exe"
rule = makefile.Rule ([product], "Linking " + product)
rule.deleteTargetFileOnClean()
rule.mDeleteTargetOnError = True
rule.mDependences += objectList
rule.mCommand += [linker]
rule.mCommand += ["-o", product]
rule.mCommand += preldflags
rule.mCommand += objectList
rule.mCommand += ldflags

make.addRule (rule)

make.addGoal("all", [product], "Building all")
make.addGoal("compile", objectList, "Compile source files")


make.runGoal(maxParallelJobs, maxParallelJobs == 1)

postVariableMapping = dict(
  MACHINE_PATH='/Users/alejandrocalderonaveitua/autosar/trampoline/machines',
  ARCH_PATH='/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7',
  BOARD_PATH='/Users/alejandrocalderonaveitua/autosar/trampoline/machines/virt-v7/armv7ve',
  TARGET='virt-v7/armv7ve'
)




make.printErrorCountAndExitOnError()

#----------------------------------------------------------------------
#-- End of build.py
#----------------------------------------------------------------------
